# 050 are Private networks according to RTR: http://www.rtr.at/index.php?S=050&id=4506&L=&submit_TK=Suchen
# 67 and 68 are not completely mobile services. 
# some ranges are used and some are note alocated, details: http://www.rtr.at/index.php?S=067&id=4506&L=&submit_TK=Suchen

Austria = {
  :range => 1..3,
  :default => 3,
  '1' => {:description => 'Wien'},
  '50' => {:description => 'Private Networks'}, 
  '57' => {:description => '-'},
  '59' => {:description => '-'},
  # '67' => {:description => 'Mobile Services'},
  # '68' => {:description => 'Mobile Services'},
  '89' => {:description => 'Routing Number'},
  '316' => {:description => 'Graz'},
  # '501' => {:description => '-'},
  # '502' => {:description => '-'},
  # '503' => {:description => '-'},
  # '504' => {:description => '-'},
  # '505' => {:description => '-'},
  # '506' => {:description => '-'},
  # '507' => {:description => '-'},
  # '508' => {:description => '-'},
  # '509' => {:description => '-'},
  '512' => {:description => 'Innsbruck'},
  '517' => {:description => '-'},
  '644' => {:description => 'Mobile Services'},
  '650' => {:description => 'Mobile Services Tele.Ring'},
  '651' => {:description => 'Mobile Services'},
  '652' => {:description => 'Mobile Services'},
  '653' => {:description => 'Mobile Services'},
  '655' => {:description => 'Mobile Services'},
  '657' => {:description => 'Mobile Services'},
  '659' => {:description => 'Mobile Services'},
  '660' => {:description => 'Mobile Services H3G'},
  '661' => {:description => 'Mobile Services'},
  '662' => {:description => 'Salzburg'},
  '663' => {:description => 'Mobile Services'},
  '664' => {:description => 'Mobile Services A1'},
  '665' => {:description => 'Mobile Services'},
  '666' => {:description => 'Mobile Services'},
  '667' => {:description => 'Mobile Services'},
  '668' => {:description => 'Mobile Services'},
  '669' => {:description => 'Mobile Services'},
  '676' => {:description => 'Mobile Services T-Mobile'},
  '680' => {:description => 'Mobile Services Bob'},
  '681' => {:description => 'Mobile Services Yesss!'},
  '699' => {:description => 'Mobile Services Orange'},
  '710' => {:description => 'Service Number'},
  '711' => {:description => 'Service Number'},
  '718' => {:description => 'Service Number'},
  '720' => {:description => 'VoIP'},
  '730' => {:description => 'Service Number'},
  '732' => {:description => 'Linz'},
  '740' => {:description => 'Service Number'},
  '780' => {:description => 'Service Number'},
  '800' => {:description => 'Service Number'},
  '802' => {:description => 'Service Number'},
  '804' => {:description => 'Service Number'},
  '810' => {:description => 'Service Number'},
  '820' => {:description => 'Service Number'},
  '821' => {:description => 'Service Number'},
  '828' => {:description => 'Service Number'},
  '900' => {:description => 'Service Number'},
  '901' => {:description => 'Service Number'},
  '930' => {:description => 'Service Number'},
  '931' => {:description => 'Service Number'},
  '939' => {:description => 'Service Number'}
}