# encoding: utf-8

Germany = {
  :range => 2..3,
  :default => 3,
  '10' => {:description => 'Call-By-Call'},
  '11' => {:description => 'formerly Value Added Services'},
  '12' => {:description => 'Innovative Services'},
  '13' => {:description => 'Voting and Lottery Numbers'},
  '30' => {:description => 'Berlin'},
  '32' => {:description => 'Non Geographical Numbers'},
  '40' => {:description => 'Hamburg'},
  '69' => {:description => 'Frankfurt am Main'},
  '89' => {:description => 'München'},
  '150' => {:description => 'Group3G/Quam'},
  '151' => {:description => 'T-Mobile'},
  '152' => {:description => 'Vodafone'},
  '155' => {:description => 'E-Plus'},
  '156' => {:description => 'Mobilcom'},
  '157' => {:description => 'E-Plus'},
  '159' => {:description => 'O2'},
  '160' => {:description => 'T-Mobile'},
  '161' => {:description => 'C-Netz'},
  '162' => {:description => 'Vodafone'},
  '163' => {:description => 'E-Plus'},
  '164' => {:description => 'Cityruf'},
  '165' => {:description => 'Quix'},
  '166' => {:description => 'Telmi'},
  '168' => {:description => 'Scall'},
  '169' => {:description => 'Cityruf, Scall, Skyper (e*cityruf, e*message, e*skyper)'},
  '170' => {:description => 'T-Mobile'},
  '171' => {:description => 'T-Mobile'},
  '172' => {:description => 'Vodafone'},
  '173' => {:description => 'Vodafone'},
  '174' => {:description => 'Vodafone'},
  '175' => {:description => 'T-Mobile'},
  '176' => {:description => 'O2 Germany'},
  '177' => {:description => 'E-Plus'},
  '178' => {:description => 'E-Plus'},
  '179' => {:description => 'O2 Germany'},
  '181' => {:description => 'IVPNs'},
  '182' => {:description => 'Closed User Group'},
  '183' => {:description => 'Closed User Group'},
  '184' => {:description => 'Closed User Group'},
  '185' => {:description => 'Closed User Group'},
  '186' => {:description => 'Closed User Group'},
  '187' => {:description => 'Closed User Group'},
  '189' => {:description => 'Closed User Group'},
  '190' => {:description => 'former Premium Rate Services'},
  '191' => {:description => 'Online Services'},
  '192' => {:description => 'Online Services'},
  '193' => {:description => 'Online Services'},
  '194' => {:description => 'Online Services'},
  '199' => {:description => 'Network-Internal Traffic Control'},
  '201' => {:description => 'Essen'},
  '202' => {:description => 'Wuppertal'},
  '203' => {:description => 'Duisburg'},
  '208' => {:description => 'Mühlheim an der Ruhr'},
  '209' => {:description => 'Gelsenkirchen'},
  '211' => {:description => 'Düsseldorf'},
  '212' => {:description => 'Solingen'},
  '214' => {:description => 'Leverkusen'},
  '221' => {:description => 'Köln'},
  '228' => {:description => 'Bonn'},
  '231' => {:description => 'Dortmund'},
  '234' => {:description => 'Bochum'},
  '241' => {:description => 'Aachen'},
  '251' => {:description => 'Münster'},
  '261' => {:description => 'Koblenz'},
  '271' => {:description => 'Siegen'},
  '281' => {:description => 'Wesel'},
  '291' => {:description => 'Meschede'},
  '310' => {:description => 'Test Number Long Distance'},
  '311' => {:description => 'Test Number Local'},
  '335' => {:description => 'Frankfurt (Oder)'},
  '340' => {:description => 'Dessau'},
  '341' => {:description => 'Leipzig'},
  '345' => {:description => 'Halle (Saale)'},
  '351' => {:description => 'Dresden'},
  '355' => {:description => 'Cottbus'},
  '361' => {:description => 'Erfurt'},
  '365' => {:description => 'Gera'},
  '371' => {:description => 'Chemnitz'},
  '375' => {:description => 'Zwickau'},
  '381' => {:description => 'Rostock'},
  '385' => {:description => 'Schwerin'},
  '391' => {:description => 'Magdeburg'},
  '395' => {:description => 'Neubrandenburg'},
  '421' => {:description => 'Bremen'},
  '431' => {:description => 'Kiel'},
  '441' => {:description => 'Oldenburg'},
  '461' => {:description => 'Flensburg'},
  '471' => {:description => 'Bremerhaven'},
  '481' => {:description => 'Heide'},
  '491' => {:description => 'Leer'},
  '511' => {:description => 'Hannover'},
  '521' => {:description => 'Bielefeld'},
  '531' => {:description => 'Braunschweig'},
  '541' => {:description => 'Osnabrück'},
  '551' => {:description => 'Göttingen'},
  '561' => {:description => 'Kassel'},
  '571' => {:description => 'Minden'},
  '581' => {:description => 'Uelzen'},
  '591' => {:description => 'Lingen (Ems)'},
  '611' => {:description => 'Wiesbaden'},
  '621' => {:description => 'Mannheim / Ludwigshafen'},
  '631' => {:description => 'Kaiserslautern'},
  '641' => {:description => 'Gießen'},
  '651' => {:description => 'Trier'},
  '661' => {:description => 'Fulda'},
  '671' => {:description => 'Bad Kreuznach'},
  '681' => {:description => 'Saarbrücken'},
  '700' => {:description => 'Personal Numbers'},
  '701' => {:description => 'Personal Numbers, reserved'},
  '711' => {:description => 'Stuttgart'},
  '721' => {:description => 'Karlsruhe'},
  '731' => {:description => 'Ulm'},
  '741' => {:description => 'Rottweil'},
  '751' => {:description => 'Ravensburg'},
  '761' => {:description => 'Freiburg im Breisgau'},
  '771' => {:description => 'Donaueschingen'},
  '781' => {:description => 'Offenburg'},
  '791' => {:description => 'Schwäbisch Hall'},
  '800' => {:description => 'Toll-Free Numbers'},
  '801' => {:description => 'Toll-Free Numbers, reserved'},
  '811' => {:description => 'Hallbergmoos'},
  '821' => {:description => 'Augsburg'},
  '831' => {:description => 'Kempten'},
  '841' => {:description => 'Ingolstadt'},
  '851' => {:description => 'Passau'},
  '861' => {:description => 'Traunstein'},
  '871' => {:description => 'Landshut'},
  '881' => {:description => 'Weilheim in Oberbayern'},
  '900' => {:description => 'Premium Rate Numbers'},
  '901' => {:description => 'Premium Rate Numbers, reserved'},
  '902' => {:description => 'Replacement for 0137/0138'},
  '906' => {:description => 'Donauwörth'},
  '911' => {:description => 'Nürnberg'},
  '921' => {:description => 'Bayreuth'},
  '931' => {:description => 'Würzburg'},
  '941' => {:description => 'Regensburg'},
  '951' => {:description => 'Bamberg'},
  '961' => {:description => 'Weiden'},
  '971' => {:description => 'Bad Kissingen'},
  '981' => {:description => 'Ansbach'},
  '991' => {:description => 'Deggendorf'}
}
