# encoding: utf-8

NANP = {
  :range => 3..3,
  :default => 3,
  '201' => {:abbreviation => 'New Jersey', :description => '[New Jersey] ([Union City], [Teaneck], [New Milford], [Jersey City], [Hoboken], [Bayonne], [Hackensack], [Ridgewood], and northe', :info => 'en.wikipedia.com.org/wiki/Area_codes_201_and_551'},
  '202' => {:abbreviation => 'Washington, D.C.', :description => '[Washington, D.C.] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_202'},
  '203' => {:abbreviation => 'Connecticut', :description => '[Connecticut] ([Bridgeport], [New Haven], [Waterbury] and southwestern Connecticut; proposed overlay with [475])', :info => 'en.wikipedia.com.org/wiki/Area_code_203'},
  '204' => {:abbreviation => 'Manitoba', :description => '[Manitoba] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_204'},
  '205' => {:abbreviation => 'Alabama', :description => '[Alabama] (Originally the code for the entire state, it still covers the largest city, [Birmingham]; [Tuscaloosa]; western and c', :info => 'en.wikipedia.com.org/wiki/Area_code_205'},
  '206' => {:abbreviation => 'Washington', :description => '[Washington] (All of Bainbridge, Mercer, and [Vashon islands], and the cities of Burien, Des Moines, Lake Forest Park, Normandy ', :info => 'en.wikipedia.com.org/wiki/Area_code_206'},
  '207' => {:abbreviation => 'Maine', :description => '[Maine] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_207'},
  '208' => {:abbreviation => 'Idaho', :description => '[Idaho] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_208'},
  '209' => {:abbreviation => 'California', :description => '[California] (Stockton, Merced, Modesto, Tracy, San Andreas and central California)', :info => 'en.wikipedia.com.org/wiki/Area_code_209'},
  '210' => {:abbreviation => 'Texas', :description => '[Texas] ([San Antonio] area)', :info => 'en.wikipedia.com.org/wiki/Area_code_210'},
  '211' => {:abbreviation => '', :description => 'Community Services Hotline (e.g., crisis line, United Way etc..)', :info => 'en.wikipedia.com.org/wiki/N11_code'},
  '212' => {:abbreviation => 'New York', :description => '[New York] (New York City: [Manhattan] only; overlays with [646] and [917])', :info => 'en.wikipedia.com.org/wiki/Area_code_212'},
  '213' => {:abbreviation => 'California', :description => '[California] (central Los Angeles)', :info => 'en.wikipedia.com.org/wiki/Area_code_213'},
  '214' => {:abbreviation => 'Texas', :description => '[Texas] ([Dallas] area, overlays with [469] and [972])', :info => 'en.wikipedia.com.org/wiki/Area_codes_214,_469,_and_972'},
  '215' => {:abbreviation => 'Pennsylvania', :description => '[Pennsylvania] ([Philadelphia] area including its suburbs in eastern [Montgomery County] and most of [Bucks County], overlays wi', :info => 'en.wikipedia.com.org/wiki/Area_codes_215_and_267'},
  '216' => {:abbreviation => 'Ohio', :description => '[Ohio] ([Cleveland] area)', :info => 'en.wikipedia.com.org/wiki/Area_code_216'},
  '217' => {:abbreviation => 'Illinois', :description => '[Illinois] (Champaign, Decatur, Urbana, Springfield and central Illinois)', :info => 'en.wikipedia.com.org/wiki/Area_code_217'},
  '218' => {:abbreviation => 'Minnesota', :description => '[Minnesota] (Duluth, Thief River Falls, Brainerd, International Falls and northern Minnesota)', :info => 'en.wikipedia.com.org/wiki/Area_code_218'},
  '219' => {:abbreviation => 'Indiana', :description => '[Indiana] Northwestern (Chesterton, Crown Point, Gary, Hammond, Hobart, Merrillville, Michigan City, Portage, Valparaiso)', :info => 'en.wikipedia.com.org/wiki/Area_code_219'},
  '224' => {:abbreviation => 'Illinois', :description => '[Illinois] (Waukegan, Des Plaines, northwest [Chicago] suburbs and northeastern Illinois, overlays with [847])', :info => 'en.wikipedia.com.org/wiki/Area_codes_847_and_224'},
  '225' => {:abbreviation => 'Louisiana', :description => '[Louisiana] (Baton Rouge, New Roads, White Castle and central eastern Louisiana)', :info => 'en.wikipedia.com.org/wiki/Area_code_225'},
  '226' => {:abbreviation => 'Ontario', :description => '[Ontario] (London, Windsor, Kitchener-Waterloo and part of southwestern Ontario; overlays with [519] in October 2006)', :info => 'en.wikipedia.com.org/wiki/Area_codes_519_and_226'},
  '227' => {:abbreviation => 'Maryland', :description => '[Maryland] (This code is scheduled to provide numbering relief to [area code 240] but no date has been assigned for this to go i', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '228' => {:abbreviation => 'Mississippi', :description => '[Mississippi] (Gulfport, Pascagoula, Biloxi, Bay St Louis and southern Mississippi gulf coast)', :info => 'en.wikipedia.com.org/wiki/Area_code_228'},
  '229' => {:abbreviation => 'Georgia', :description => '[Georgia] (Albany, Valdosta, Bainbridge, Americus, Fitzgerald and southwestern Georgia). Split from [912]', :info => 'en.wikipedia.com.org/wiki/Area_code_229'},
  '231' => {:abbreviation => 'Michigan', :description => '[Michigan] (Traverse City, Ludington, Muskegon, Petoskey and northwestern Michigan)', :info => 'en.wikipedia.com.org/wiki/Area_code_231'},
  '234' => {:abbreviation => 'Ohio', :description => '[Ohio] (Youngstown, Warren, Akron, Canton and northeastern Ohio, overlays with 330)', :info => 'en.wikipedia.com.org/wiki/Area_codes_234_and_330'},
  '236' => {:abbreviation => 'British Columbia', :description => '[British Columbia] (This code is reserved to provide numbering relief to [area code 250 and 778][[1]] but no date has been assig', :info => 'en.wikipedia.com.org/wiki/Area_code_236'},
  '239' => {:abbreviation => 'Florida', :description => '[Florida] (southwest coast: all of [Lee County], [Collier County], mainland [Monroe County] excluding [Florida Keys]; includes C', :info => 'en.wikipedia.com.org/wiki/Area_code_239'},
  '240' => {:abbreviation => 'Maryland', :description => '[Maryland] all those counties which touch the [Potomac River] including (Hagerstown, Rockville, Cumberland and western Maryland,', :info => 'en.wikipedia.com.org/wiki/Area_codes_240_and_301'},
  '242' => {:abbreviation => '', :description => 'The Bahamas', :info => 'en.wikipedia.com.org/wiki/The_Bahamas'},
  '246' => {:abbreviation => '', :description => 'Barbados', :info => 'en.wikipedia.com.org/wiki/Barbados'},
  '248' => {:abbreviation => 'Michigan', :description => '[Michigan] (Troy, Oakland County, Pontiac, Southfield, Rochester Hills and northwestern Detroit suburbs, overlays with [947])', :info => 'en.wikipedia.com.org/wiki/Area_codes_248_and_947'},
  '250' => {:abbreviation => 'British Columbia', :description => '[British Columbia] (except [Vancouver] area). Overlays with area code [778] (see [604])', :info => 'en.wikipedia.com.org/wiki/Area_code_250'},
  '251' => {:abbreviation => 'Alabama', :description => '[Alabama] ([Mobile], [Jackson], [Brewton] and southwestern Alabama)', :info => 'en.wikipedia.com.org/wiki/Area_code_251'},
  '252' => {:abbreviation => 'North Carolina', :description => '[North Carolina] (Greenville, Kitty Hawk, Rocky Mount and northeastern North Carolina)', :info => 'en.wikipedia.com.org/wiki/Area_code_252'},
  '253' => {:abbreviation => 'Washington', :description => '[Washington] (Lakewood, Tacoma, Auburn, Puyallup, Enumclaw, Spanaway and south Seattle suburbs)', :info => 'en.wikipedia.com.org/wiki/Area_code_253'},
  '254' => {:abbreviation => 'Texas', :description => '[Texas] ([Waco], Killeen, Belton, and Stephenville)', :info => 'en.wikipedia.com.org/wiki/Area_code_254'},
  '256' => {:abbreviation => 'Alabama', :description => '[Alabama] ([Huntsville], [Decatur], [Cullman], [Gadsden], [Florence], [Anniston] and northern and eastern Alabama)', :info => 'en.wikipedia.com.org/wiki/Area_code_256'},
  '260' => {:abbreviation => 'Indiana', :description => '[Indiana] ([Fort Wayne], [New Haven], [Decatur], [Angola], [Huntington], [Wabash] and northeastern Indiana)', :info => 'en.wikipedia.com.org/wiki/Area_code_260'},
  '262' => {:abbreviation => 'Wisconsin', :description => '[Wisconsin] (Menomonee Falls, Waukesha, Racine, Kenosha and southeastern Wisconsin excluding Milwaukee County)', :info => 'en.wikipedia.com.org/wiki/Area_code_262'},
  '264' => {:abbreviation => '', :description => 'Anguilla', :info => 'en.wikipedia.com.org/wiki/Anguilla'},
  '267' => {:abbreviation => 'Pennsylvania', :description => '[Pennsylvania] ([Philadelphia] area including its suburbs in eastern [Montgomery County] and most of [Bucks County], overlays wi', :info => 'en.wikipedia.com.org/wiki/Area_codes_215_and_267'},
  '268' => {:abbreviation => '', :description => 'Antigua and Barbuda', :info => 'en.wikipedia.com.org/wiki/Antigua_and_Barbuda'},
  '269' => {:abbreviation => 'Michigan', :description => '[Michigan] (Battle Creek, Benton Harbor, Allegan, Hastings, Kalamazoo, St Joseph, and southwestern Michigan)', :info => 'en.wikipedia.com.org/wiki/Area_code_269'},
  '270' => {:abbreviation => 'Kentucky', :description => '[Kentucky] (Elizabethtown, Paducah, Bowling Green, Hopkinsville, Owensboro, Henderson, and western Kentucky)', :info => 'en.wikipedia.com.org/wiki/Area_code_270'},
  '276' => {:abbreviation => 'Virginia', :description => '[Virginia] (Abingdon, Wytheville, Martinsville, Bluefield and southwestern Virginia)', :info => 'en.wikipedia.com.org/wiki/Area_code_276'},
  '281' => {:abbreviation => 'Texas', :description => '[Texas] (Houston area, overlays with [713] and [832])', :info => 'en.wikipedia.com.org/wiki/Area_codes_281,_713,_and_832'},
  '283' => {:abbreviation => 'Ohio', :description => '[Ohio] (Cincinnati, Middletown, Hamilton, Norwood, Lebanon and southwestern Ohio. Overlay of code [283] postponed. Currently [51', :info => 'en.wikipedia.com.org/wiki/Area_code_513'},
  '284' => {:abbreviation => '', :description => 'British Virgin Islands', :info => 'en.wikipedia.com.org/wiki/British_Virgin_Islands'},
  '289' => {:abbreviation => 'Ontario', :description => '[Ontario] ([Niagara Peninsula], [Hamilton], [GTA] suburbs and central southeastern Ontario, overlays with [905])', :info => 'en.wikipedia.com.org/wiki/Area_codes_905_and_289'},
  '301' => {:abbreviation => 'Maryland', :description => '[Maryland] all those counties which touch the [Potomac River] ([Hagerstown], [Frederick], [Rockville], Cumberland and western Ma', :info => 'en.wikipedia.com.org/wiki/Area_codes_240_and_301'},
  '302' => {:abbreviation => 'Delaware', :description => '[Delaware] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_302'},
  '303' => {:abbreviation => 'Colorado', :description => '[Colorado] (Boulder, Longmont, Aurora, Denver and central Colorado, overlays with [720])', :info => 'en.wikipedia.com.org/wiki/Area_codes_303_and_720'},
  '304' => {:abbreviation => 'West Virginia', :description => '[West Virginia] (to be overlaid by [681])', :info => 'en.wikipedia.com.org/wiki/Area_codes_304_and_681'},
  '305' => {:abbreviation => 'Florida', :description => '[Florida] (all of [Miami-Dade County] and the [Florida Keys] of [Monroe County]: [Miami], [Homestead], [Coral Gables], [Key West', :info => 'en.wikipedia.com.org/wiki/Area_codes_305_and_786'},
  '306' => {:abbreviation => 'Saskatchewan', :description => '[Saskatchewan] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_306'},
  '307' => {:abbreviation => 'Wyoming', :description => '[Wyoming] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_307'},
  '308' => {:abbreviation => 'Nebraska', :description => '[Nebraska] (North Platte, Scottsbluff, McCook, Kearney, Grand Island and western Nebraska)', :info => 'en.wikipedia.com.org/wiki/Area_code_308'},
  '309' => {:abbreviation => 'Illinois', :description => '[Illinois] (Peoria, Bloomington-Normal, Moline, Rock Island, Galesburg and central western Illinois)', :info => 'en.wikipedia.com.org/wiki/Area_code_309'},
  '310' => {:abbreviation => 'California', :description => '[California] ([Malibu], [Torrance], [South Bay], [Beverly Hills], [Santa Monica], [Catalina Island], the [Los Angeles Westside],', :info => 'en.wikipedia.com.org/wiki/Area_codes_310_and_424'},
  '311' => {:abbreviation => '', :description => 'Local or government non-emergency use, City Hall in some localities.', :info => 'en.wikipedia.com.org/wiki/N11_code'},
  '312' => {:abbreviation => 'Illinois', :description => '[Illinois] (downtown [Chicago])', :info => 'en.wikipedia.com.org/wiki/Area_code_312'},
  '313' => {:abbreviation => 'Michigan', :description => '[Michigan] (Dearborn, Detroit and its inner suburbs)', :info => 'en.wikipedia.com.org/wiki/Area_code_313'},
  '314' => {:abbreviation => 'Missouri', :description => '[Missouri] ([St. Louis], Florissant, Crestwood, Affton, and surrounding Missouri suburbs)', :info => 'en.wikipedia.com.org/wiki/Area_code_314'},
  '315' => {:abbreviation => 'New York', :description => '[New York] (Syracuse, Utica, Watertown, and north central New York)', :info => 'en.wikipedia.com.org/wiki/Area_code_315'},
  '316' => {:abbreviation => 'Kansas', :description => '[Kansas] (Wichita, Augusta, El Dorado, Mulvane and the Wichita surrounding area)', :info => 'en.wikipedia.com.org/wiki/Area_code_316'},
  '317' => {:abbreviation => 'Indiana', :description => '[Indiana] (Indianapolis, Noblesville, Greenwood, Mooresville, Beech Grove and central Indiana)', :info => 'en.wikipedia.com.org/wiki/Area_code_317'},
  '318' => {:abbreviation => 'Louisiana', :description => '[Louisiana] (Shreveport, Monroe, Alexandria, Fisher, Tallulah and northern Louisiana)', :info => 'en.wikipedia.com.org/wiki/Area_code_318'},
  '319' => {:abbreviation => 'Iowa', :description => '[Iowa] (Burlington, Iowa City, Cedar Rapids, Waterloo and east central and southeastern Iowa)', :info => 'en.wikipedia.com.org/wiki/Area_code_319'},
  '320' => {:abbreviation => 'Minnesota', :description => '[Minnesota] (St. Cloud, Alexandria, Morris, Hutchinson, Sandstone, Appleton and central Minnesota)', :info => 'en.wikipedia.com.org/wiki/Area_code_320'},
  '321' => {:abbreviation => 'Florida', :description => '[Florida] (Orlando, Cocoa Beach, St Cloud and central eastern Florida, partial overlay with [407])', :info => 'en.wikipedia.com.org/wiki/Area_code_321'},
  '323' => {:abbreviation => 'California', :description => '[California] (Florence and [Los Angeles] excluding downtown Los Angeles; see also [213])', :info => 'en.wikipedia.com.org/wiki/Area_code_323'},
  '325' => {:abbreviation => 'Texas', :description => '[Texas] (Abilene, Sweetwater, Snyder, San Angelo)', :info => 'en.wikipedia.com.org/wiki/Area_code_325'},
  '330' => {:abbreviation => 'Ohio', :description => '[Ohio] (Youngstown, Warren, Akron, Canton and northeastern Ohio, overlays with [234])', :info => 'en.wikipedia.com.org/wiki/Area_codes_234_and_330'},
  '331' => {:abbreviation => 'Illinois', :description => '[Illinois] (West Suburban Chicago, overlays [630])', :info => 'en.wikipedia.com.org/wiki/Area_codes_630_and_331'},
  '334' => {:abbreviation => 'Alabama', :description => '[Alabama] ([Montgomery], [Auburn], [Opelika], [Dothan], [Selma] and southeastern Alabama)', :info => 'en.wikipedia.com.org/wiki/Area_code_334'},
  '336' => {:abbreviation => 'North Carolina', :description => '[North Carolina] (Winston-Salem, Greensboro, North Wilkesboro, Roxboro, and northwest North Carolina)', :info => 'en.wikipedia.com.org/wiki/Area_code_336'},
  '337' => {:abbreviation => 'Louisiana', :description => '[Louisiana] (Leesville, Lake Charles, Lafayette, New Iberia, Opelousas, De Ridder and southwestern Louisiana), split from [318] ', :info => 'en.wikipedia.com.org/wiki/Area_code_337'},
  '339' => {:abbreviation => 'Massachusetts', :description => '[Massachusetts] ([Saugus], [Norwood], [Waltham], [Woburn], east central Massachusetts and other [Boston] suburbs along [Route 12', :info => 'en.wikipedia.com.org/wiki/Area_code_339'},
  '340' => {:abbreviation => '', :description => 'United States Virgin Islands', :info => 'en.wikipedia.com.org/wiki/United_States_Virgin_Islands'},
  '341' => {:abbreviation => 'California', :description => '[California] This Area code is scheduled to provide numbering relief for Area code [510] but no date has been assigned for this ', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '343' => {:abbreviation => 'Ontario', :description => '[Ontario] ([Ottawa], eastern and southeastern Ontario) This area code is scheduled to provide numbering relief to area code 613 ', :info => 'en.wikipedia.com.org/wiki/Area_code_613'},
  '345' => {:abbreviation => '', :description => 'Cayman Islands', :info => 'en.wikipedia.com.org/wiki/Cayman_Islands'},
  '347' => {:abbreviation => 'New York', :description => '[New York] (New York City except [Manhattan] generally for mobile phones; overlays with [718] and [917])', :info => 'en.wikipedia.com.org/wiki/Area_code_347'},
  '351' => {:abbreviation => 'Massachusetts', :description => '[Massachusetts] ([Fitchburg], [Peabody] and northeastern Massachusetts, overlays with [978])', :info => 'en.wikipedia.com.org/wiki/Area_code_351'},
  '352' => {:abbreviation => 'Florida', :description => '[Florida] (Gainesville, Ocala, Inverness, Dunnellon and central Florida)', :info => 'en.wikipedia.com.org/wiki/Area_code_352'},
  '360' => {:abbreviation => 'Washington', :description => '[Washington] (Bellingham, Belfair, Bremerton, Aberdeen, Olympia and western Washington except the greater Seattle area, which us', :info => 'en.wikipedia.com.org/wiki/Area_code_360'},
  '361' => {:abbreviation => 'Texas', :description => '[Texas] (Corpus Christi, Victoria, George West and [South Texas])', :info => 'en.wikipedia.com.org/wiki/Area_code_361'},
  '364' => {:abbreviation => 'Kentucky', :description => '[Kentucky] west of the [Pennyrile Parkway], beginning April 1, 2010. Includes [Paducah]; splits with [270].', :info => 'en.wikipedia.com.org/wiki/Area_code_364'},
  '369' => {:abbreviation => 'California', :description => '[California] This code is scheduled to provide numbering relief to Area code [707], but no date has been assigned for this to go', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '380' => {:abbreviation => 'Ohio', :description => '[Ohio] This Area code is scheduled to provide numbering relief to Area code [614] but no date has been assigned for this to go i', :info => 'en.wikipedia.com.org/wiki/Area_code_614'},
  '385' => {:abbreviation => 'Utah', :description => '[Utah] ([Wasatch Front], overlays with [801]).', :info => 'en.wikipedia.com.org/wiki/Area_codes_385_and_801'},
  '386' => {:abbreviation => 'Florida', :description => '[Florida] (Daytona Beach, Lake City, Live Oak, Crescent City and northern and eastern Florida)', :info => 'en.wikipedia.com.org/wiki/Area_code_386'},
  '401' => {:abbreviation => 'Rhode Island', :description => '[Rhode Island] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_401'},
  '402' => {:abbreviation => 'Nebraska', :description => '[Nebraska] ([Lincoln], [Norfolk], [Omaha], [Superior], [Crofton] and eastern Nebraska)', :info => 'en.wikipedia.com.org/wiki/Area_code_402'},
  '403' => {:abbreviation => 'Alberta', :description => '[Alberta] ([Calgary], [Banff], [Red Deer], [Medicine Hat], [Lethbridge], [Brooks] and southern Alberta, overlays with province-w', :info => 'en.wikipedia.com.org/wiki/Area_code_403'},
  '404' => {:abbreviation => 'Georgia', :description => '[Georgia] (Atlanta area inside [Interstate 285] perimeter, overlay by [678])', :info => 'en.wikipedia.com.org/wiki/Area_code_404'},
  '405' => {:abbreviation => 'Oklahoma', :description => '[Oklahoma] ([Oklahoma City], [Stillwater], [Edmond], [Norman], [Shawnee], [Chickasha] and central Oklahoma)', :info => 'en.wikipedia.com.org/wiki/Area_code_405'},
  '406' => {:abbreviation => 'Montana', :description => '[Montana] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_406'},
  '407' => {:abbreviation => 'Florida', :description => '[Florida] ([Orlando], [Cocoa Beach], [St. Cloud] and central eastern Florida, partial overlay with [321])', :info => 'en.wikipedia.com.org/wiki/Area_code_407'},
  '410' => {:abbreviation => 'Maryland', :description => '[Maryland] all those counties which touch the [Chesapeake Bay] or [Atlantic Ocean] ([Annapolis], [Baltimore], [Salisbury] and ea', :info => 'en.wikipedia.com.org/wiki/Area_codes_410_and_443'},
  '411' => {:abbreviation => '', :description => 'Directory Services; 1-areacode-555-1212 is also used.', :info => 'en.wikipedia.com.org/wiki/N11_code'},
  '414' => {:abbreviation => 'Wisconsin', :description => '[Wisconsin] ([Milwaukee] and nearby suburbs)', :info => 'en.wikipedia.com.org/wiki/Area_code_414'},
  '415' => {:abbreviation => 'California', :description => '[California] ([San Francisco], [Marin County])', :info => 'en.wikipedia.com.org/wiki/Area_code_415'},
  '416' => {:abbreviation => 'Ontario', :description => '[Ontario] ([Toronto]; overlays with [647])', :info => 'en.wikipedia.com.org/wiki/Area_codes_416_and_647'},
  '419' => {:abbreviation => 'Ohio', :description => '[Ohio] ([Toledo], [Sylvania], [Mansfield], [Lima], [Findlay],[Bryan], [Sandusky], [Bowling Green] and northwestern Ohio, overlay', :info => 'en.wikipedia.com.org/wiki/Area_codes_419_and_567'},
  '434' => {:abbreviation => 'Virginia', :description => '[Virginia] ([Lynchburg], [Danville], [Farmville], [South Hill], [Charlottesville]; southside and south-central Virginia)', :info => 'en.wikipedia.com.org/wiki/Area_code_434'},
  '438' => {:abbreviation => 'Quebec', :description => '[Quebec] ([Montreal] area; overlays with [514]; will also overlay [450] beginning in 2010)', :info => 'en.wikipedia.com.org/wiki/Area_codes_514_and_438'},
  '441' => {:abbreviation => '', :description => 'Bermuda', :info => 'en.wikipedia.com.org/wiki/Bermuda'},
  '442' => {:abbreviation => 'California', :description => '[California]; this overlay Area code is scheduled to provide numbering relief to area code [760] in late 2009', :info => 'en.wikipedia.com.org/wiki/Area_code_442'},
  '443' => {:abbreviation => 'Maryland', :description => '[Maryland] all those counties which touch [Chesapeake Bay] or the [Atlantic Ocean] ([Annapolis], [Baltimore], [Salisbury] and ea', :info => 'en.wikipedia.com.org/wiki/Area_codes_410_and_443'},
  '445' => {:abbreviation => 'Pennsylvania', :description => '[Pennsylvania] ([Philadelphia] area, overlays with [215] and [267]) Area code 445 is listed in the North American Numbering Plan', :info => 'en.wikipedia.com.org/wiki/Area_code_445'},
  '447' => {:abbreviation => '', :description => 'Illinois', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '450' => {:abbreviation => 'Quebec', :description => '[Quebec] (central southern Quebec including the city of [Laval] but excluding [Montreal])', :info => 'en.wikipedia.com.org/wiki/Area_code_450'},
  '456' => {:abbreviation => '', :description => 'Inbound international calls for carrier-specific services', :info => 'en.wikipedia.com.org/wiki/Area_code_456'},
  '458' => {:abbreviation => 'Oregon', :description => '[Oregon] Overlay of [Area code 541] to be introduced in 2010', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '464' => {:abbreviation => 'Illinois', :description => '[Illinois] Overlay of [Area code 708]', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '473' => {:abbreviation => '', :description => 'Grenada', :info => 'en.wikipedia.com.org/wiki/Grenada'},
  '475' => {:abbreviation => '', :description => 'future overlay of Connecticut\'s [203] ([Bridgeport], [New Haven], [Waterbury]); roughly Fairfield and New Haven counties', :info => 'en.wikipedia.com.org/wiki/Area_code_475'},
  '500' => {:abbreviation => 'Personal Communications Services', :description => '[Personal Communications Services]', :info => 'en.wikipedia.com.org/wiki/Area_code_500'},
  '501' => {:abbreviation => 'Arkansas', :description => '[Arkansas] (Little Rock, Hot Springs and central Arkansas)', :info => 'en.wikipedia.com.org/wiki/Area_code_501'},
  '502' => {:abbreviation => 'Kentucky', :description => '[Kentucky] (Louisville, Frankfort, Shelbyville, Bardstown and north central Kentucky)', :info => 'en.wikipedia.com.org/wiki/Area_code_502'},
  '503' => {:abbreviation => 'Oregon', :description => '[Oregon] (Portland, Salem, Rainier, St. Helens, Tillamook, Astoria and northwestern Oregon, overlays with [971])', :info => 'en.wikipedia.com.org/wiki/Area_codes_503_and_971'},
  '504' => {:abbreviation => 'Louisiana', :description => '[Louisiana] ([New Orleans], Metairie, Kenner and surrounding areas)', :info => 'en.wikipedia.com.org/wiki/Area_code_504'},
  '505' => {:abbreviation => 'New Mexico', :description => '[New Mexico]: Albuquerqueâ€“Santa Fe metro area and northwestern New Mexico', :info => 'en.wikipedia.com.org/wiki/Area_code_505'},
  '506' => {:abbreviation => 'New Brunswick', :description => '[New Brunswick]', :info => 'en.wikipedia.com.org/wiki/Area_code_506'},
  '507' => {:abbreviation => 'Minnesota', :description => '[Minnesota] (Rochester, Mankato, Worthington, Marshall; southern Minnesota)', :info => 'en.wikipedia.com.org/wiki/Area_code_507'},
  '508' => {:abbreviation => 'Massachusetts', :description => '[Massachusetts] ([Worcester], [New Bedford] and [southeastern Massachusetts], overlays with [774])', :info => 'en.wikipedia.com.org/wiki/Area_code_508'},
  '509' => {:abbreviation => 'Washington', :description => '[Washington] (All of eastern Washington, including Spokane, the Tri-Cities, Yakima, Wenatchee, Walla Walla, Pullman, and Ellensb', :info => 'en.wikipedia.com.org/wiki/Area_code_509'},
  '510' => {:abbreviation => 'California', :description => '[California] ([Hayward], [Berkeley], [Alameda], [Oakland], [Richmond] and [Fremont] areas)', :info => 'en.wikipedia.com.org/wiki/Area_code_510'},
  '511' => {:abbreviation => '', :description => 'Rarely used, is directed to local police non-emergency services in some communities. Starting to be used as the [5-1-1] service.', :info => 'en.wikipedia.com.org/wiki/N11_code'},
  '512' => {:abbreviation => 'Texas', :description => '[Texas] ([Austin], Lampasas, Bastrop, Milam and Central Texas). Formerly included [San Antonio] too', :info => 'en.wikipedia.com.org/wiki/Area_code_512'},
  '513' => {:abbreviation => 'Ohio', :description => '[Ohio] (Cincinnati, Middletown, Hamilton, Norwood, Lebanon and southwestern Ohio. Planned overlay with [283] is postponed) Forme', :info => 'en.wikipedia.com.org/wiki/Area_code_513'},
  '514' => {:abbreviation => 'Quebec', :description => '[Quebec] (The entire [Island of Montreal], ÃŽle Perrot and [ÃŽle Bizard]); overlays with [438] as of November 4, 2006', :info => 'en.wikipedia.com.org/wiki/Area_codes_514_and_438'},
  '515' => {:abbreviation => 'Iowa', :description => '[Iowa] (Des Moines, Ames, Fort Dodge, Jefferson, Algona, Indianola and north central Iowa)', :info => 'en.wikipedia.com.org/wiki/Area_code_515'},
  '516' => {:abbreviation => 'New York', :description => '[New York] ([Nassau County])', :info => 'en.wikipedia.com.org/wiki/Area_code_516'},
  '517' => {:abbreviation => 'Michigan', :description => '[Michigan] (Lansing, Jackson, Charlotte, Coldwater, Howell, Deerfield, Addison and south central Michigan)', :info => 'en.wikipedia.com.org/wiki/Area_code_517'},
  '518' => {:abbreviation => 'New York', :description => '[New York] (Plattsburgh, Saranac Lake, Albany and northeastern New York)', :info => 'en.wikipedia.com.org/wiki/Area_code_518'},
  '519' => {:abbreviation => 'Ontario', :description => '[Ontario] (London, Windsor, Kitchener-Waterloo, Cambridge and most of southwestern Ontario; overlays with [Area code 226])', :info => 'en.wikipedia.com.org/wiki/Area_codes_519_and_226'},
  '520' => {:abbreviation => 'Arizona', :description => '[Arizona] ([Tucson] and southeastern Arizona)', :info => 'en.wikipedia.com.org/wiki/Area_code_520'},
  '530' => {:abbreviation => 'California', :description => '[California] (Alturas, Chico, Davis, Redding, Placerville, Truckee and northeastern California)', :info => 'en.wikipedia.com.org/wiki/Area_code_530'},
  '533' => {:abbreviation => '', :description => 'reserved for [Personal Communications Services]', :info => 'en.wikipedia.com.org/wiki/Area_code_533'},
  '540' => {:abbreviation => 'Virginia', :description => '[Virginia] ([Roanoke], [Blacksburg], [Harrisonburg], [Winchester], [Fredericksburg] and north-central Virginia) but no longer th', :info => 'en.wikipedia.com.org/wiki/Area_code_540'},
  '541' => {:abbreviation => 'Oregon', :description => '[Oregon] (Medford, Eugene, Bend, Ontario, Burns and all of Oregon except northwestern Oregon)', :info => 'en.wikipedia.com.org/wiki/Area_code_541'},
  '551' => {:abbreviation => 'New Jersey', :description => '[New Jersey] (Northern New Jersey, Bergen and Hudson counties)', :info => 'en.wikipedia.com.org/wiki/Area_codes_201_and_551'},
  '555' => {:abbreviation => '', :description => 'Reserved for directory assistance applications.', :info => 'en.wikipedia.com.org/wiki/555_(telephone_number)'},
  '557' => {:abbreviation => 'Missouri', :description => '[Missouri] Overlay of [Area code 314]', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '559' => {:abbreviation => 'California', :description => '[California] (Fresno, Madera, Hanford, Visalia, Tulare and central California; the middle section of the San Joaquin Valley)', :info => 'en.wikipedia.com.org/wiki/Area_code_559'},
  '561' => {:abbreviation => 'Florida', :description => '[Florida] (exactly [Palm Beach County]: West Palm Beach, Boca Raton, Boynton Beach, Delray Beach, Belle Glade)', :info => 'en.wikipedia.com.org/wiki/Area_code_561'},
  '562' => {:abbreviation => 'California', :description => '[California] ([Long Beach], [Lakewood], [Bellflower], [Norwalk] and southeastern [Los Angeles] suburbs)', :info => 'en.wikipedia.com.org/wiki/Area_code_562'},
  '563' => {:abbreviation => 'Iowa', :description => '[Iowa] (Decorah, Dubuque, Clinton, Davenport and eastern and northeastern Iowa)', :info => 'en.wikipedia.com.org/wiki/Area_code_563'},
  '564' => {:abbreviation => 'Washington', :description => '[Washington] ([Western Washington])â€”planned.', :info => 'en.wikipedia.com.org/wiki/Area_code_564'},
  '567' => {:abbreviation => 'Ohio', :description => '[Ohio] (Toledo, Mansfield, Lima, Findlay, Bryan, Sandusky and northwestern Ohio, overlays with [419])', :info => 'en.wikipedia.com.org/wiki/Area_codes_419_and_567'},
  '570' => {:abbreviation => 'Pennsylvania', :description => '[Pennsylvania] (Scranton, Williamsport, Wilkes-Barre, Nanticoke, Hazleton, Pottsville, Sunbury, Danville, Bloomsburg, Stroudsbur', :info => 'en.wikipedia.com.org/wiki/Area_code_570'},
  '571' => {:abbreviation => 'Virginia', :description => '[Virginia] ([Northern Virginia]: [Alexandria], [Arlington], [Fairfax], [Prince William] and eastern [Loudoun] counties, overlays', :info => 'en.wikipedia.com.org/wiki/Area_codes_571_and_703'},
  '573' => {:abbreviation => 'Missouri', :description => '[Missouri] (Columbia, Jefferson City, Hannibal, Cape Girardeau, Poplar Bluff, Farmington, Park Hills, Lake Ozark and eastern Mis', :info => 'en.wikipedia.com.org/wiki/Area_code_573'},
  '574' => {:abbreviation => 'Indiana', :description => '[Indiana] ([South Bend], [Logansport], [Elkhart], [Warsaw], [Nappanee] and north central Indiana)', :info => 'en.wikipedia.com.org/wiki/Area_code_574'},
  '575' => {:abbreviation => 'New Mexico', :description => '[New Mexico]: all areas outside of the Albuquerqueâ€“Santa Fe metro area and northwestern New Mexico', :info => 'en.wikipedia.com.org/wiki/Area_code_575'},
  '580' => {:abbreviation => 'Oklahoma', :description => '[Oklahoma] ([Ponca City], Guymon, Enid, Lawton, Ardmore, Sayre, Elk City, and southern and western Oklahoma)', :info => 'en.wikipedia.com.org/wiki/Area_code_580'},
  '585' => {:abbreviation => 'New York', :description => '[New York] (Rochester, Wellsville, Batavia, and western New York)', :info => 'en.wikipedia.com.org/wiki/Area_code_585'},
  '586' => {:abbreviation => 'Michigan', :description => '[Michigan] ([Warren], [Sterling Heights] and [Macomb County], split from [810])', :info => 'en.wikipedia.com.org/wiki/Area_code_586'},
  '587' => {:abbreviation => 'Alberta', :description => '[Alberta] (Overlays with [403] and [780])', :info => 'en.wikipedia.com.org/wiki/Area_code_587'},
  '600' => {:abbreviation => '', :description => 'Special telecommunications needs in Canada', :info => 'en.wikipedia.com.org/wiki/Area_code_600'},
  '601' => {:abbreviation => 'Mississippi', :description => '[Mississippi] (Jackson, Meridian, Natchez, McComb, Hattiesburg and central Mississippi, overlays with [769])', :info => 'en.wikipedia.com.org/wiki/Area_codes_601_and_769'},
  '602' => {:abbreviation => 'Arizona', :description => '[Arizona] (Central [Phoenix] only)', :info => 'en.wikipedia.com.org/wiki/Area_code_602'},
  '603' => {:abbreviation => 'New Hampshire', :description => '[New Hampshire] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_603'},
  '604' => {:abbreviation => 'British Columbia', :description => '[British Columbia] ([Greater Vancouver Regional District] and [Abbotsford] overlay with [778]. [Whistler], [Chilliwack] and rema', :info => 'en.wikipedia.com.org/wiki/Area_code_604'},
  '605' => {:abbreviation => 'South Dakota', :description => '[South Dakota] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_605'},
  '606' => {:abbreviation => 'Kentucky', :description => '[Kentucky] ([Ashland], [Hazard], [Somerset], [London], [Corbin], [Pikeville], [Maysville] and eastern Kentucky)', :info => 'en.wikipedia.com.org/wiki/Area_code_606'},
  '607' => {:abbreviation => 'New York', :description => '[New York] (Binghamton, Elmira, Bath, Norwich, Oneonta, Ithaca, and south central New York)', :info => 'en.wikipedia.com.org/wiki/Area_code_607'},
  '608' => {:abbreviation => 'Wisconsin', :description => '[Wisconsin] (Madison, La Crosse, Platteville, Beloit and southwestern Wisconsin)', :info => 'en.wikipedia.com.org/wiki/Area_code_608'},
  '609' => {:abbreviation => 'New Jersey', :description => '[New Jersey] (Atlantic City, Browns Mills, Trenton, and central &amp; southeastern New Jersey)', :info => 'en.wikipedia.com.org/wiki/Area_code_609'},
  '610' => {:abbreviation => 'Pennsylvania', :description => '[Pennsylvania] (Reading, Chester and southeastern Pennsylvania, overlays with [484] and [835])', :info => 'en.wikipedia.com.org/wiki/Area_codes_484,_610,_and_835'},
  '611' => {:abbreviation => '', :description => 'Repair Service', :info => 'en.wikipedia.com.org/wiki/N11_code'},
  '612' => {:abbreviation => 'Minnesota', :description => '[Minnesota] (Central Minneapolis, Fort Snelling, St Anthony and Richfield)', :info => 'en.wikipedia.com.org/wiki/Area_code_612'},
  '613' => {:abbreviation => 'Ontario', :description => '[Ontario] ([Ottawa], eastern and southeastern Ontario)', :info => 'en.wikipedia.com.org/wiki/Area_code_613'},
  '614' => {:abbreviation => 'Ohio', :description => '[Ohio] (Columbus area)', :info => 'en.wikipedia.com.org/wiki/Area_code_614'},
  '615' => {:abbreviation => 'Tennessee', :description => '[Tennessee] (Nashville, Murfreesboro, Springfield, Lebanon, Dickson and north central Tennessee), split from [901] in 1954.', :info => 'en.wikipedia.com.org/wiki/Area_code_615'},
  '616' => {:abbreviation => 'Michigan', :description => '[Michigan] ([Grand Rapids], [Holland], [Greenville], [Grand Haven], [Zeeland], [Ionia] and southwestern Michigan)', :info => 'en.wikipedia.com.org/wiki/Area_code_616'},
  '617' => {:abbreviation => 'Massachusetts', :description => '[Massachusetts] ([Boston], [Cambridge], east central Massachusetts and close-in Boston suburbs, overlays with [857])', :info => 'en.wikipedia.com.org/wiki/Area_code_617'},
  '618' => {:abbreviation => 'Illinois', :description => '[Illinois] (Alton, Belleville, Carbondale, Centralia, Mount Vernon and [southern Illinois])', :info => 'en.wikipedia.com.org/wiki/Area_code_618'},
  '619' => {:abbreviation => 'California', :description => '[California] (Southern and eastern suburbs and southern portion of the city of [San Diego]) Former area code for areas now cover', :info => 'en.wikipedia.com.org/wiki/Area_code_619'},
  '620' => {:abbreviation => 'Kansas', :description => '[Kansas] (Dodge City, Great Bend, Parsons, Liberal and southern Kansas not including the [Wichita] metropolitan area)', :info => 'en.wikipedia.com.org/wiki/Area_code_620'},
  '623' => {:abbreviation => 'Arizona', :description => '[Arizona] (Glendale, Buckeye, Peoria, western Phoenix area and western Phoenix suburbs only)', :info => 'en.wikipedia.com.org/wiki/Area_code_623'},
  '626' => {:abbreviation => 'California', :description => '[California] (Arcadia, Temple City, Covina, Pasadena and eastern Los Angeles suburbs)', :info => 'en.wikipedia.com.org/wiki/Area_code_626'},
  '627' => {:abbreviation => 'California', :description => '[California] This Area code is scheduled to provide numbering relief to Area code [707] but no date has been assigned for this t', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '628' => {:abbreviation => 'California', :description => '[California] This Area code is scheduled to provide numbering relief to Area code [415] but no date has been assigned for this t', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '630' => {:abbreviation => 'Illinois', :description => '[Illinois] (Aurora, Naperville, and other Western [Chicago] suburbs, overlays with [331])', :info => 'en.wikipedia.com.org/wiki/Area_codes_630_and_331'},
  '631' => {:abbreviation => 'New York', :description => '[New York] ([Suffolk County]), split from [516]', :info => 'en.wikipedia.com.org/wiki/Area_code_631'},
  '636' => {:abbreviation => 'Missouri', :description => '[Missouri] (St. Charles, Chesterfield, Union, De Soto, Troy and east central Missouri)', :info => 'en.wikipedia.com.org/wiki/Area_code_636'},
  '641' => {:abbreviation => 'Iowa', :description => '[Iowa] (Mason City, Oskaloosa, Creston, Pella, Ottumwa, Britt, Clear Lake, Fairfield and central Iowa)', :info => 'en.wikipedia.com.org/wiki/Area_code_641'},
  '646' => {:abbreviation => 'New York', :description => '[New York] (New York City: Manhattan only; cell phone overlays with [212] and [917])', :info => 'en.wikipedia.com.org/wiki/Area_code_646'},
  '647' => {:abbreviation => 'Ontario', :description => '[Ontario] ([Toronto]; overlays with [416])', :info => 'en.wikipedia.com.org/wiki/Area_codes_416_and_647'},
  '649' => {:abbreviation => '', :description => 'Turks and Caicos Islands', :info => 'en.wikipedia.com.org/wiki/Turks_and_Caicos_Islands'},
  '650' => {:abbreviation => 'California', :description => '[California] ([San Mateo], [Palo Alto], [Redwood City], [Menlo Park], [Mountain View] and southern San Francisco suburbs)', :info => 'en.wikipedia.com.org/wiki/Area_code_650'},
  '651' => {:abbreviation => 'Minnesota', :description => '[Minnesota] (St Paul, Lindstrom, Red Wing, Hastings and east central Minnesota)', :info => 'en.wikipedia.com.org/wiki/Area_code_651'},
  '657' => {:abbreviation => 'California', :description => '[California] Created to provide numbering relief to Area code [714] beginning [September 23], [2008].', :info => 'en.wikipedia.com.org/wiki/Area_codes_657_and_714'},
  '659' => {:abbreviation => 'Alabama', :description => '[Alabama] This Area code is scheduled to provide numbering relief to Area code [205] but no date has been assigned for this to g', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '660' => {:abbreviation => 'Missouri', :description => '[Missouri] (Marshall, Sedalia, Macon, Trenton, Maryville, Bethany and north central Missouri)', :info => 'en.wikipedia.com.org/wiki/Area_code_660'},
  '661' => {:abbreviation => 'California', :description => '[California] (Bakersfield, Mojave, Santa Clarita, Palmdale and south central California)', :info => 'en.wikipedia.com.org/wiki/Area_code_661'},
  '662' => {:abbreviation => 'Mississippi', :description => '[Mississippi] (Greenville, Tupelo, Winona, Columbus, Holly Springs and northern Mississippi)', :info => 'en.wikipedia.com.org/wiki/Area_code_662'},
  '664' => {:abbreviation => '', :description => 'Montserrat', :info => 'en.wikipedia.com.org/wiki/Montserrat'},
  '667' => {:abbreviation => 'Maryland', :description => '[Maryland] This Area code is scheduled to provide numbering relief to Area code [443] but no date has been assigned for this to ', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '669' => {:abbreviation => 'California', :description => '[California] This Area code is scheduled to provide numbering relief to Area code [408] but no date has been assigned for this t', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '670' => {:abbreviation => '', :description => 'Northern Mariana Islands', :info => 'en.wikipedia.com.org/wiki/Northern_Mariana_Islands'},
  '671' => {:abbreviation => '', :description => 'Guam', :info => 'en.wikipedia.com.org/wiki/Guam'},
  '678' => {:abbreviation => 'Georgia', :description => '[Georgia] (all of [metro Atlanta], overlays both [404] and [770] and in the future [470])', :info => 'en.wikipedia.com.org/wiki/Area_code_678'},
  '679' => {:abbreviation => 'Michigan', :description => '[Michigan] This Area code is scheduled to provide numbering relief to Area code [313] but no date has been assigned for this to ', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '681' => {:abbreviation => 'West Virginia', :description => '[West Virginia] (taking full effect in 2009; overlay of 304)', :info => 'en.wikipedia.com.org/wiki/Area_codes_304_and_681'},
  '682' => {:abbreviation => 'Texas', :description => '[Texas] (Fort Worth, Arlington, Grandview, Weatherford, Rhome, overlays with [817])', :info => 'en.wikipedia.com.org/wiki/Area_codes_682_and_817'},
  '684' => {:abbreviation => '', :description => 'American Samoa', :info => 'en.wikipedia.com.org/wiki/American_Samoa'},
  '689' => {:abbreviation => 'Florida', :description => '[Florida] This Area code is scheduled to provide numbering relief to Area code [407] but no date has been assigned for this to g', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '700' => {:abbreviation => '', :description => 'Long Distance carrier use for pre-subscribing phone numbers, 1-700-555-4141 most often gives a recorded message indicating the d', :info => 'en.wikipedia.com.org/wiki/Area_code_700'},
  '701' => {:abbreviation => 'North Dakota', :description => '[North Dakota] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_701'},
  '702' => {:abbreviation => 'Nevada', :description => '[Nevada] (almost all of [Clark County], including all of the [Las Vegas] Valley, including [Henderson] and [Boulder City])', :info => 'en.wikipedia.com.org/wiki/Area_code_702'},
  '703' => {:abbreviation => 'Virginia', :description => '[Virginia] ([Northern Virginia]: suburbs of Washington including [Alexandria], [Arlington], [Fairfax], [Prince William] and east', :info => 'en.wikipedia.com.org/wiki/Area_codes_571_and_703'},
  '704' => {:abbreviation => 'North Carolina', :description => '[North Carolina] (Charlotte, Gastonia, Concord, Salisbury, and south central North Carolina, overlaid by [980]), formerly includ', :info => 'en.wikipedia.com.org/wiki/Area_codes_704_and_980'},
  '705' => {:abbreviation => 'Ontario', :description => '[Ontario] ([northeastern] and [central]â€”[North Bay], [Sudbury], [Sault Ste. Marie], [Timmins], [Barrie])', :info => 'en.wikipedia.com.org/wiki/Area_code_705'},
  '706' => {:abbreviation => 'Georgia', :description => '[Georgia] (Augusta, Lincolnton, Columbus, LaGrange, Rome, Dalton, Thomaston and northern and west central Georgia), overlayed wi', :info => 'en.wikipedia.com.org/wiki/Area_code_706'},
  '707' => {:abbreviation => 'California', :description => '[California] (North Bay, Vallejo, Santa Rosa, Fort Bragg, Crescent City, Eureka, Ukiah and northwestern California)', :info => 'en.wikipedia.com.org/wiki/Area_code_707'},
  '708' => {:abbreviation => 'Illinois', :description => '[Illinois] (Chicago Heights, Evergreen Park, Tinley Park, Elmwood Park, Cicero, Oak Forest, Oak Park, Berwyn, and southern and i', :info => 'en.wikipedia.com.org/wiki/Area_code_708'},
  '709' => {:abbreviation => 'Newfoundland and Labrador', :description => '[Newfoundland and Labrador]', :info => 'en.wikipedia.com.org/wiki/Area_code_709'},
  '710' => {:abbreviation => '', :description => 'U.S. Government Special Services', :info => 'en.wikipedia.com.org/wiki/Area_code_710'},
  '711' => {:abbreviation => 'Telecommunications device for the deaf', :description => '[Telecommunications device for the deaf]/Relay Service for TTY to Voice and Voice to TTY', :info => 'en.wikipedia.com.org/wiki/N11_code'},
  '712' => {:abbreviation => 'Iowa', :description => '[Iowa] (Estherville, Council Bluffs, Sioux City, Sheldon, Denison and western Iowa)', :info => 'en.wikipedia.com.org/wiki/Area_code_712'},
  '713' => {:abbreviation => 'Texas', :description => '[Texas] (Houston area, overlays with [281] and [832])', :info => 'en.wikipedia.com.org/wiki/Area_codes_281,_713,_and_832'},
  '714' => {:abbreviation => 'California', :description => '[California] (Santa Ana, Huntington Beach, Orange, Garden Grove, Tustin, Anaheim, and northern Orange County, overlays with [657', :info => 'en.wikipedia.com.org/wiki/Area_code_714'},
  '715' => {:abbreviation => 'Wisconsin', :description => '[Wisconsin] (Rhinelander, Wausau, Eau Claire, Rice Lake, Ashland and northern Wisconsin)', :info => 'en.wikipedia.com.org/wiki/Area_code_715'},
  '716' => {:abbreviation => 'New York', :description => '[New York] (Buffalo, Jamestown, Niagara Falls, Tonawanda, Olean, and western New York)', :info => 'en.wikipedia.com.org/wiki/Area_code_716'},
  '717' => {:abbreviation => 'Pennsylvania', :description => '[Pennsylvania] ([Harrisburg], [Gettysburg], [Lancaster], [York] and south-central Pennsylvania)', :info => 'en.wikipedia.com.org/wiki/Area_code_717'},
  '718' => {:abbreviation => 'New York', :description => '[New York] (New York City: [Brooklyn], [Queens], [The Bronx], and [Staten Island] only; overlays with [347] and [917])', :info => 'en.wikipedia.com.org/wiki/Area_code_718'},
  '719' => {:abbreviation => 'Colorado', :description => '[Colorado] (Leadville, Pueblo, Colorado Springs, Trinidad, Rocky Ford, La Junta and southeastern Colorado)', :info => 'en.wikipedia.com.org/wiki/Area_code_719'},
  '720' => {:abbreviation => 'Colorado', :description => '[Colorado] (Boulder, Longmont, Aurora, Denver and central Colorado, overlays with [303])', :info => 'en.wikipedia.com.org/wiki/Area_code_720'},
  '724' => {:abbreviation => 'Pennsylvania', :description => '[Pennsylvania] ([New Castle], [Washington], [Uniontown] and south western Pennsylvania, overlays with [878])', :info => 'en.wikipedia.com.org/wiki/Area_code_724'},
  '727' => {:abbreviation => 'Florida', :description => '[Florida] (all of [Pinellas County] including Clearwater, St Petersburg, Dunedin; coastal-only parts of [Pasco County])', :info => 'en.wikipedia.com.org/wiki/Area_code_727'},
  '730' => {:abbreviation => 'Illinois', :description => '[Illinois] Proposed overlay of Area code [618]', :info => 'en.wikipedia.com.org/wiki/Area_code_730'},
  '731' => {:abbreviation => 'Tennessee', :description => '[Tennessee] ([West Tennessee] excluding greater Memphis: Union City, Jackson, Dyersburg, Martin, Brownsville, Paris, Bolivar), s', :info => 'en.wikipedia.com.org/wiki/Area_code_731'},
  '732' => {:abbreviation => 'New Jersey', :description => '[New Jersey] (New Brunswick, Neptune, Lakewood, and east central New Jersey, overlays with [848])', :info => 'en.wikipedia.com.org/wiki/Area_code_732'},
  '734' => {:abbreviation => 'Michigan', :description => '[Michigan] (Ann Arbor, Canton, Plymouth, Monroe, Wayne, Ypsilanti, Romulus and southwestern Detroit suburbs)', :info => 'en.wikipedia.com.org/wiki/Area_code_734'},
  '737' => {:abbreviation => 'Texas', :description => '[Texas] This Area code is scheduled to provide numbering relief to area code [512] but no date has been assigned for this to go ', :info => 'en.wikipedia.com.org/wiki/Area_code_737'},
  '740' => {:abbreviation => 'Ohio', :description => '[Ohio] (Jackson, Lancaster, Marietta, Marion, Cambridge, Zanesville, New Castle, Athens, and southeastern Ohio)', :info => 'en.wikipedia.com.org/wiki/Area_code_740'},
  '747' => {:abbreviation => 'California', :description => '[California] (San Fernando Valley) This Area code is scheduled to provide numbering relief to area code [818] but no date has be', :info => 'en.wikipedia.com.org/wiki/Area_code_747'},
  '754' => {:abbreviation => 'Florida', :description => '[Florida] (All of [Broward County]: [Fort Lauderdale], [Hollywood], [Coral Springs], overlays with [954])', :info => 'en.wikipedia.com.org/wiki/Area_code_754'},
  '757' => {:abbreviation => 'Virginia', :description => '[Virginia] ([Hampton Roads] area and [Eastern Shore]; until the mid-1990s, a part of [804])', :info => 'en.wikipedia.com.org/wiki/Area_code_757'},
  '758' => {:abbreviation => '', :description => 'Saint Lucia', :info => 'en.wikipedia.com.org/wiki/Saint_Lucia'},
  '760' => {:abbreviation => 'California', :description => '[California] (Bishop, Ridgecrest, Barstow, eastern portions of San Bernardino and Riverside counties (including the Palm Springs', :info => 'en.wikipedia.com.org/wiki/Area_code_760'},
  '762' => {:abbreviation => 'Georgia', :description => '[Georgia] (Augusta, Columbus, Lagrange, Rome, Dalton and northern and west central Georgia) Overlay code for [area code 706]', :info => 'en.wikipedia.com.org/wiki/Area_code_762'},
  '763' => {:abbreviation => 'Minnesota', :description => '[Minnesota] (Maple Grove, Monticello, Elk River, Fridley, Blaine, and northwest Minneapolis area)', :info => 'en.wikipedia.com.org/wiki/Area_code_763'},
  '764' => {:abbreviation => 'California', :description => '[California] This Area code is scheduled to provide numbering relief to Area code [650] but no date has been assigned for this t', :info => 'en.wikipedia.com.org/wiki/Area_code_764'},
  '765' => {:abbreviation => 'Indiana', :description => '[Indiana] (Lafayette, Marion, Muncie, Richmond and central Indiana excluding Indianapolis)', :info => 'en.wikipedia.com.org/wiki/Area_code_765'},
  '767' => {:abbreviation => '', :description => 'Dominica', :info => 'en.wikipedia.com.org/wiki/Dominica'},
  '769' => {:abbreviation => 'Mississippi', :description => '[Mississippi] (overlays with [601])', :info => 'en.wikipedia.com.org/wiki/Area_code_769'},
  '770' => {:abbreviation => 'Georgia', :description => '[Georgia] (Marietta, Cedartown, Gainesville, and central north Georgia ([suburban] [metro Atlanta])', :info => 'en.wikipedia.com.org/wiki/Area_code_770'},
  '772' => {:abbreviation => 'Florida', :description => '[Florida] (Vero Beach, Port Saint Lucie, Fort Pierce, Sebastian, Stuart and central eastern Florida)', :info => 'en.wikipedia.com.org/wiki/Area_code_772'},
  '773' => {:abbreviation => 'Illinois', :description => '[Illinois] (City of [Chicago], excluding downtown; see also [312])', :info => 'en.wikipedia.com.org/wiki/Area_code_773'},
  '774' => {:abbreviation => 'Massachusetts', :description => '[Massachusetts] ([Worcester], [New Bedford] and [southeastern Massachusetts], overlays with [508])', :info => 'en.wikipedia.com.org/wiki/Area_code_774'},
  '775' => {:abbreviation => 'Nevada', :description => '[Nevada] (Reno, Elko, Ely and all of Nevada except Clark County and the Las Vegas Valley)', :info => 'en.wikipedia.com.org/wiki/Area_code_775'},
  '778' => {:abbreviation => 'British Columbia', :description => '[British Columbia]. Overlays both area code [604] and area code [250] (ie. the entire province of [British Columbia]).', :info => 'en.wikipedia.com.org/wiki/Area_code_778'},
  '779' => {:abbreviation => 'Illinois', :description => '[Illinois] ([Crystal Lake], [Rockford], [Joliet], and other outlying suburbs of [Chicago]; It overlays with [815])', :info => 'en.wikipedia.com.org/wiki/Area_codes_815_and_779'},
  '780' => {:abbreviation => 'Alberta', :description => '[Alberta] ([Edmonton], [Jasper], [Grande Prairie], [Peace River] and northern Alberta, overlay\'s with [587] along with Southern ', :info => 'en.wikipedia.com.org/wiki/Area_code_780'},
  '781' => {:abbreviation => 'Massachusetts', :description => '[Massachusetts] ([Saugus], [Norwood], [Waltham], [Woburn], east central Massachusetts and other [Boston] suburbs along [Route 12', :info => 'en.wikipedia.com.org/wiki/Area_code_781'},
  '784' => {:abbreviation => '', :description => 'Saint Vincent and the Grenadines', :info => 'en.wikipedia.com.org/wiki/Saint_Vincent_and_the_Grenadines'},
  '785' => {:abbreviation => 'Kansas', :description => '[Kansas] (Colby, Topeka, Salina, Manhattan, Lawrence and northern Kansas)', :info => 'en.wikipedia.com.org/wiki/Area_code_785'},
  '786' => {:abbreviation => 'Florida', :description => '[Florida] (exactly [Miami-Dade County], not [Florida Keys]; overlays with most of [305])', :info => 'en.wikipedia.com.org/wiki/Area_code_786'},
  '787' => {:abbreviation => '', :description => 'Puerto Rico', :info => 'en.wikipedia.com.org/wiki/Puerto_Rico'},
  '801' => {:abbreviation => 'Utah', :description => '[Utah] ([Wasatch Front], overlays with [385])', :info => 'en.wikipedia.com.org/wiki/Area_codes_385_and_801'},
  '802' => {:abbreviation => 'Vermont', :description => '[Vermont] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_802'},
  '803' => {:abbreviation => 'South Carolina', :description => '[South Carolina] (Columbia, Rock Hill, Sumter, Aiken and central South Carolina)', :info => 'en.wikipedia.com.org/wiki/Area_code_803'},
  '804' => {:abbreviation => 'Virginia', :description => '[Virginia] (the [Richmond metropolitan area]). Formerly, it included Hampton Roads and southside area too', :info => 'en.wikipedia.com.org/wiki/Area_code_804'},
  '805' => {:abbreviation => 'California', :description => '[California] ([San Luis Obispo], [Santa Barbara], [Isla Vista], [Ventura], [Santa Paula]; southwest central coastal California)', :info => 'en.wikipedia.com.org/wiki/Area_code_805'},
  '806' => {:abbreviation => 'Texas', :description => '[Texas] (Amarillo, Lubbock, Canadian, Perryton, Shamrock, Dalhart and [Texas Panhandle])', :info => 'en.wikipedia.com.org/wiki/Area_code_806'},
  '807' => {:abbreviation => 'Ontario', :description => '[Ontario] ([Northwestern Ontario]: [Thunder Bay], [Kenora], [Dryden], [Greenstone])', :info => 'en.wikipedia.com.org/wiki/Area_code_807'},
  '808' => {:abbreviation => 'Hawaii', :description => '[Hawaii] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_808'},
  '809' => {:abbreviation => '', :description => 'Dominican Republic', :info => 'en.wikipedia.com.org/wiki/Dominican_Republic'},
  '810' => {:abbreviation => 'Michigan', :description => '[Michigan] (Port Huron, Flint, Lapeer, and Michigan "Thumb", (originally split from [313] and included areas that later became [', :info => 'en.wikipedia.com.org/wiki/Area_code_810'},
  '811' => {:abbreviation => '', :description => 'Mobile customer service on some North American cellular carriers, also used as a 9-1-1 like emergency number to handle distress ', :info => 'en.wikipedia.com.org/wiki/N11_code'},
  '812' => {:abbreviation => 'Indiana', :description => '[Indiana] (Southern Indiana, including [Bloomington], [Evansville], [Jeffersonville], [New Albany], and [Terre Haute]).', :info => 'en.wikipedia.com.org/wiki/Area_code_812'},
  '813' => {:abbreviation => 'Florida', :description => '[Florida] (all of [Hillsborough County], including [Tampa], [Temple Terrace], and [Plant City]; inland areas of [Pasco County], ', :info => 'en.wikipedia.com.org/wiki/Area_code_813'},
  '814' => {:abbreviation => 'Pennsylvania', :description => '[Pennsylvania] (Morrisdale, Erie, Warren, State College, Altoona, Johnstown, Meyersdale, Johnsonburg, St. Marys, Ridgway, DuBois', :info => 'en.wikipedia.com.org/wiki/Area_code_814'},
  '815' => {:abbreviation => 'Illinois', :description => '[Illinois] (La Salle, De Kalb, Rockford, Freeport and northern Illinois including parts of the Chicago area such as Joliet, Plai', :info => 'en.wikipedia.com.org/wiki/Area_codes_815_and_779'},
  '816' => {:abbreviation => 'Missouri', :description => '[Missouri] (Kansas City, St Joseph, Independence, Harrisonville and west central Missouri)', :info => 'en.wikipedia.com.org/wiki/Area_code_816'},
  '817' => {:abbreviation => 'Texas', :description => '[Texas] (Fort Worth, Arlington, Grandview, Weatherford, Rhome, overlays with [682])', :info => 'en.wikipedia.com.org/wiki/Area_codes_682_and_817'},
  '818' => {:abbreviation => 'California', :description => '[California] (Glendale, San Fernando, Burbank and northern Los Angeles suburbs)', :info => 'en.wikipedia.com.org/wiki/Area_code_818'},
  '819' => {:abbreviation => 'Quebec', :description => '[Quebec] ([Abitibi-TÃ©miscamingue], [Mauricie], [Outaouais] and [Estrie])', :info => 'en.wikipedia.com.org/wiki/Area_code_819'},
  '825' => {:abbreviation => '', :description => 'reserved for future usage in [Alberta].', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '828' => {:abbreviation => 'North Carolina', :description => '[North Carolina] (Hickory, Asheville, Waynesville, [Franklin], Murphy and western North Carolina)', :info => 'en.wikipedia.com.org/wiki/Area_code_828'},
  '829' => {:abbreviation => '', :description => 'Dominican Republic', :info => 'en.wikipedia.com.org/wiki/Dominican_Republic'},
  '830' => {:abbreviation => 'Texas', :description => '[Texas] (Del Rio, Uvalde, New Braunfels, Kerrville, Eagle Pass and southwest Texas)', :info => 'en.wikipedia.com.org/wiki/Area_code_830'},
  '831' => {:abbreviation => 'California', :description => '[California] (Salinas, Hollister, Monterey, Santa Cruz and central western coastal California)', :info => 'en.wikipedia.com.org/wiki/Area_code_831'},
  '832' => {:abbreviation => 'Texas', :description => '[Texas] (Houston area, overlays with [281] and [713])', :info => 'en.wikipedia.com.org/wiki/Area_codes_281,_713,_and_832'},
  '835' => {:abbreviation => 'Pennsylvania', :description => '[Pennsylvania] (overlays with [484] and [610])', :info => 'en.wikipedia.com.org/wiki/Area_codes_484,_610,_and_835'},
  '843' => {:abbreviation => 'South Carolina', :description => '[South Carolina] (Florence, Myrtle Beach, Charleston, Isle of Palms, Hilton Head Island and eastern South Carolina)', :info => 'en.wikipedia.com.org/wiki/Area_code_843'},
  '845' => {:abbreviation => 'New York', :description => '[New York] (Rockland, Poughkeepsie, Middletown, West Point, Newburgh and southeastern New York, Catskills Region west to Margare', :info => 'en.wikipedia.com.org/wiki/Area_code_845'},
  '847' => {:abbreviation => 'Illinois', :description => '[Illinois] ([Arlington Heights], [Buffalo Grove], Wauconda, Waukegan, Des Plaines, north and northwest Chicago suburbs and north', :info => 'en.wikipedia.com.org/wiki/Area_codes_847_and_224'},
  '848' => {:abbreviation => 'New Jersey', :description => '[New Jersey] (New Brunswick, Neptune, Lakewood, and east central New Jersey, overlays with [732])', :info => 'en.wikipedia.com.org/wiki/Area_codes_732_and_848'},
  '849' => {:abbreviation => '', :description => 'Dominican Republic', :info => 'en.wikipedia.com.org/wiki/Dominican_Republic'},
  '850' => {:abbreviation => 'Florida', :description => '[Florida] (Pensacola, Tallahassee, Panama City and the Florida panhandle)', :info => 'en.wikipedia.com.org/wiki/Area_code_850'},
  '856' => {:abbreviation => 'New Jersey', :description => '[New Jersey] (Vineland, Cherry Hill, Camden, Millville, and southwestern New Jersey)', :info => 'en.wikipedia.com.org/wiki/Area_code_856'},
  '857' => {:abbreviation => 'Massachusetts', :description => '[Massachusetts] ([Boston], [Cambridge], east central Massachusetts and close-in Boston suburbs, overlays with [617])', :info => 'en.wikipedia.com.org/wiki/Area_code_857'},
  '858' => {:abbreviation => 'California', :description => '[California] (Del Mar, La Jolla and other inner northern San Diego suburbs, northern half of city of [San Diego])', :info => 'en.wikipedia.com.org/wiki/Area_code_858'},
  '859' => {:abbreviation => 'Kentucky', :description => '[Kentucky] (Lexington, Richmond, Danville, Covington, Florence, Mount Sterling and north central Kentucky)', :info => 'en.wikipedia.com.org/wiki/Area_code_859'},
  '860' => {:abbreviation => 'Connecticut', :description => '[Connecticut] (Bristol, Hartford, Norwich and northern and eastern Connecticut)', :info => 'en.wikipedia.com.org/wiki/Area_code_860'},
  '862' => {:abbreviation => 'New Jersey', :description => '[New Jersey] (portions of Bergen, Essex, Morris, Passaic and Sussex counties in northern New Jersey)', :info => 'en.wikipedia.com.org/wiki/Area_code_862'},
  '863' => {:abbreviation => 'Florida', :description => '[Florida] (Lakeland, Avon Park, Clewiston, [Bartow], Sebring, Winter Haven and south central Florida)', :info => 'en.wikipedia.com.org/wiki/Area_code_863'},
  '864' => {:abbreviation => 'South Carolina', :description => '[South Carolina] (Greenville, Spartanburg, Anderson and Upstate South Carolina)', :info => 'en.wikipedia.com.org/wiki/Area_code_864'},
  '865' => {:abbreviation => 'Tennessee', :description => '[Tennessee] (Knoxville, Gatlinburg, Newport, Jefferson City, Oak Ridge, Rockwood and central [East Tennessee]), split from [423]', :info => 'en.wikipedia.com.org/wiki/Area_code_865'},
  '867' => {:abbreviation => 'Yukon', :description => '[Yukon], [Northwest Territories] and [Nunavut]', :info => 'en.wikipedia.com.org/wiki/Area_code_867'},
  '868' => {:abbreviation => '', :description => 'Trinidad and Tobago', :info => 'en.wikipedia.com.org/wiki/Trinidad_and_Tobago'},
  '869' => {:abbreviation => '', :description => 'Saint Kitts and Nevis', :info => 'en.wikipedia.com.org/wiki/Saint_Kitts_and_Nevis'},
  '870' => {:abbreviation => 'Arkansas', :description => '[Arkansas] (Texarkana, Jonesboro, Pine Bluff and southern, eastern and northeastern Arkansas)', :info => 'en.wikipedia.com.org/wiki/Area_code_870'},
  '872' => {:abbreviation => 'Illinois', :description => '[Illinois] This Area code is scheduled to provide numbering relief to Area code [312] but no date has been assigned for this to ', :info => 'en.wikipedia.com.org/wiki/Area_code_872'},
  '876' => {:abbreviation => '', :description => 'Jamaica', :info => 'en.wikipedia.com.org/wiki/Jamaica'},
  '878' => {:abbreviation => 'Pennsylvania', :description => '[Pennsylvania] (Pittsburgh, New Castle, and southwestern Pennsylvania, overlays with [412] and [724])', :info => 'en.wikipedia.com.org/wiki/Area_code_878'},
  '900' => {:abbreviation => 'premium-rate telephone numbers', :description => '[premium-rate telephone numbers]', :info => 'en.wikipedia.com.org/wiki/Area_code_900'},
  '901' => {:abbreviation => 'Tennessee', :description => '[Tennessee] (Memphis, Covington, Somerville and extreme southwestern Tennessee). Originally for the entire state.', :info => 'en.wikipedia.com.org/wiki/Area_code_901'},
  '902' => {:abbreviation => 'Nova Scotia', :description => '[Nova Scotia] and [Prince Edward Island]', :info => 'en.wikipedia.com.org/wiki/Area_code_902'},
  '903' => {:abbreviation => 'Texas', :description => '[Texas] (Tyler, Sherman, Longview, Marshall, Palestine, Jacksonville, Carthage, and [Northeast Texas])', :info => 'en.wikipedia.com.org/wiki/Area_code_903'},
  '904' => {:abbreviation => 'Florida', :description => '[Florida] ([Jacksonville], [St. Augustine], [Starke], [Green Cove Springs] and northeastern Florida) Formerly included entire no', :info => 'en.wikipedia.com.org/wiki/Area_code_904'},
  '905' => {:abbreviation => 'Ontario', :description => '[Ontario] ([Niagara Region], [Hamilton], [GTA] suburbs and central southeastern Ontario, overlays with [289])', :info => 'en.wikipedia.com.org/wiki/Area_code_905'},
  '906' => {:abbreviation => 'Michigan', :description => '[Michigan] ([Upper Peninsula])', :info => 'en.wikipedia.com.org/wiki/Area_code_906'},
  '907' => {:abbreviation => 'Alaska', :description => '[Alaska] (all)', :info => 'en.wikipedia.com.org/wiki/Area_code_907'},
  '908' => {:abbreviation => 'New Jersey', :description => '[New Jersey] (Alpha, Washington, Elizabeth, Warren, Plainfield and west central New Jersey)', :info => 'en.wikipedia.com.org/wiki/Area_code_908'},
  '909' => {:abbreviation => 'California', :description => '[California] (western portions of San Bernardino County, including Colton, Grand Terrace, Ontario, Claremont, Pomona, Chino, Red', :info => 'en.wikipedia.com.org/wiki/Area_code_909'},
  '910' => {:abbreviation => 'North Carolina', :description => '[North Carolina] (Fayetteville, Wilmington, Jacksonville, Lumberton and southeastern North Carolina)', :info => 'en.wikipedia.com.org/wiki/Area_code_910'},
  '911' => {:abbreviation => '', :description => 'Emergency Services', :info => 'en.wikipedia.com.org/wiki/9-1-1'},
  '912' => {:abbreviation => 'Georgia', :description => '[Georgia] (Savannah, Statesboro, Vidalia, Waycross, Brunswick, Douglas and southeastern Georgia)', :info => 'en.wikipedia.com.org/wiki/Area_code_912'},
  '913' => {:abbreviation => 'Kansas', :description => '[Kansas] ([Kansas City], [Overland Park], [Paola], [Leavenworth] and extreme eastern Kansas)', :info => 'en.wikipedia.com.org/wiki/Area_code_913'},
  '914' => {:abbreviation => 'New York', :description => '[New York] ([Westchester County])', :info => 'en.wikipedia.com.org/wiki/Area_code_914'},
  '915' => {:abbreviation => 'Texas', :description => '[Texas] (All of [El Paso County] and portion of [Hudspeth County])', :info => 'en.wikipedia.com.org/wiki/Area_code_915'},
  '916' => {:abbreviation => 'California', :description => '[California] ([Sacramento] area) Formerly included most of northern California not includin the San Francisco-Oakland area; much', :info => 'en.wikipedia.com.org/wiki/Area_code_916'},
  '917' => {:abbreviation => 'New York', :description => '[New York] (New York City; [cell phones] overlays with [212], [347], [646], and [718])', :info => 'en.wikipedia.com.org/wiki/Area_code_917'},
  '918' => {:abbreviation => 'Oklahoma', :description => '[Oklahoma] (Tulsa, Bartlesville, McAlester, Muskogee, Henryetta and northeastern Oklahoma)', :info => 'en.wikipedia.com.org/wiki/Area_code_918'},
  '919' => {:abbreviation => 'North Carolina', :description => '[North Carolina] (Raleigh, Durham, Chapel Hill, Oxford, Goldsboro and north central North Carolina)', :info => 'en.wikipedia.com.org/wiki/Area_code_919'},
  '920' => {:abbreviation => 'Wisconsin', :description => '[Wisconsin] (Appleton, Sheboygan, Oshkosh, Green Bay, Manitowoc, Fond du Lac and eastern Wisconsin)', :info => 'en.wikipedia.com.org/wiki/Area_code_920'},
  '925' => {:abbreviation => 'California', :description => '[California] (Concord, Pleasant Hill, Walnut Creek, Martinez, Livermore, Pleasanton and Dublin areas)', :info => 'en.wikipedia.com.org/wiki/Area_code_925'},
  '928' => {:abbreviation => 'Arizona', :description => '[Arizona] ([Flagstaff], [Kingman], [Prescott], [Yuma] and northern and western Arizona)', :info => 'en.wikipedia.com.org/wiki/Area_code_928'},
  '931' => {:abbreviation => 'Tennessee', :description => '[Tennessee] ([Middle Tennessee], excluding Greater Nashville: Clarksville, Columbia, Manchester, Cookeville), split from [615]', :info => 'en.wikipedia.com.org/wiki/Area_code_931'},
  '935' => {:abbreviation => 'California', :description => '[California] This Area code is scheduled to provide numbering relief to Area code [619] but no date has been assigned for this t', :info => 'en.wikipedia.com.org/wiki/Area_code_935'},
  '936' => {:abbreviation => 'Texas', :description => '[Texas] (Nacogdoches, Lufkin, Conroe, Huntsville, Center and [Southeast Texas])', :info => 'en.wikipedia.com.org/wiki/Area_code_936'},
  '937' => {:abbreviation => 'Ohio', :description => '[Ohio] (Marysville, Springfield, Dayton, Hillsboro and southwestern Ohio excluding Cincinnati area)', :info => 'en.wikipedia.com.org/wiki/Area_code_937'},
  '938' => {:abbreviation => 'Alabama', :description => '[Alabama] Overlay of [Area code 256] to be introduced in 2011', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '939' => {:abbreviation => '', :description => 'Puerto Rico', :info => 'en.wikipedia.com.org/wiki/Puerto_Rico'},
  '940' => {:abbreviation => 'Texas', :description => '[Texas] (Vernon, Wichita Falls, Denton, Gainesville, Decatur and [North Texas])', :info => 'en.wikipedia.com.org/wiki/Area_code_940'},
  '941' => {:abbreviation => 'Florida', :description => '[Florida] (Gulf Coast immediately south of [Tampa Bay]: all of [Manatee County], [Sarasota County], and [Charlotte County]; incl', :info => 'en.wikipedia.com.org/wiki/Area_code_941'},
  '947' => {:abbreviation => 'Michigan', :description => '[Michigan] (Troy, Oakland County, Pontiac, Southfield, Rochester Hills and northwestern Detroit suburbs, overlays with [248])', :info => 'en.wikipedia.com.org/wiki/Area_code_947'},
  '949' => {:abbreviation => 'California', :description => '[California] ([Laguna Niguel], [Irvine], [Lake Forest], [Newport Beach], [Corona Del Mar] and southern [Orange County])', :info => 'en.wikipedia.com.org/wiki/Area_code_949'},
  '951' => {:abbreviation => 'California', :description => '[California] (western [Riverside County], including Corona, Riverside, Temescal Canyon, Lake Elsinore, Mira Loma, Moreno Valley,', :info => 'en.wikipedia.com.org/wiki/Area_code_951'},
  '952' => {:abbreviation => 'Minnesota', :description => '[Minnesota] (Bloomington, Minnetonka, Chaska and southwest Minneapolis area)', :info => 'en.wikipedia.com.org/wiki/Area_code_952'},
  '954' => {:abbreviation => 'Florida', :description => '[Florida] (all of [Broward County]: [Fort Lauderdale], [Hollywood], [Coral Springs], overlaid by [754])', :info => 'en.wikipedia.com.org/wiki/Area_code_954'},
  '956' => {:abbreviation => 'Texas', :description => '[Texas] (Laredo, Brownsville, McAllen, Harlingen and [South Texas])', :info => 'en.wikipedia.com.org/wiki/Area_code_956'},
  '959' => {:abbreviation => 'Connecticut', :description => '[Connecticut] (Bristol, Hartford, Norwich and northern and eastern Connecticut, overlays with 860)', :info => 'en.wikipedia.com.org/wiki/Area_code_959'},
  '970' => {:abbreviation => 'Colorado', :description => '[Colorado] (Aspen, Durango, Grand Junction, Fort Collins and northern and western Colorado)', :info => 'en.wikipedia.com.org/wiki/Area_code_970'},
  '971' => {:abbreviation => 'Oregon', :description => '[Oregon] (Portland, Salem, Hillsboro, Beaverton and northwestern Oregon, overlays with [503])', :info => 'en.wikipedia.com.org/wiki/Area_code_971'},
  '972' => {:abbreviation => 'Texas', :description => '[Texas] (Dallas area, overlays with [214] and [469])', :info => 'en.wikipedia.com.org/wiki/Area_code_972'},
  '973' => {:abbreviation => 'New Jersey', :description => '[New Jersey] (Newark, Paterson and northwestern New Jersey, overlays with [862])', :info => 'en.wikipedia.com.org/wiki/Area_code_973'},
  '975' => {:abbreviation => 'Missouri', :description => '[Missouri] This area code is scheduled to provide numbering relief to code [816] but no date has been assigned for this to go in', :info => 'en.wikipedia.com.org/wiki/Area_code_975'},
  '978' => {:abbreviation => 'Massachusetts', :description => '[Massachusetts] ([Fitchburg], [Peabody] and northeastern Massachusetts, overlays with [351])', :info => 'en.wikipedia.com.org/wiki/Area_code_978'},
  '979' => {:abbreviation => 'Texas', :description => '[Texas] (Wharton, Bryan, Bay City, College Station, Lake Jackson, La Grange and Southeast Texas)', :info => 'en.wikipedia.com.org/wiki/Area_code_979'},
  '980' => {:abbreviation => 'North Carolina', :description => '[North Carolina] (Charlotte, Gastonia, Salisbury and south central North Carolina, overlays with [704])', :info => 'en.wikipedia.com.org/wiki/Area_code_980'},
  '984' => {:abbreviation => 'North Carolina', :description => '[North Carolina] This area code is scheduled to provide overlay relief to code [919] but no date has been assigned for this to g', :info => 'en.wikipedia.com.org/wiki/List_of_future_North_American_area_codes'},
  '985' => {:abbreviation => 'Louisiana', :description => '[Louisiana] (Houma, Slidell and southeastern Louisiana excluding New Orleans)', :info => 'en.wikipedia.com.org/wiki/Area_code_985'},
  '989' => {:abbreviation => 'Michigan', :description => '[Michigan] (Alpena, Mt. Pleasant, Bay City, Saginaw, Midland, Owosso and central Michigan)', :info => 'en.wikipedia.com.org/wiki/Area_code_989'}
}
