# encoding: utf-8
# Romania uses different NDC for the former monopoly (Romtelecom) and other operators (OLO - Other line operators)
# Landline starting with 2 usually mean Romtelecom, starting with 3 means OLO. 

Romania = {
	:range => 1..3,
	:default => 3,
	'21' => {:description=>"București"},
	'31' => {:description=>"București"},
	'256' => {:description=>"Timișoara"},
	'356' => {:description=>"Timișoara"},
	'711' => {:description=>"Romtelecom VoIP"},
	'720' => {:description=>"Mobile Vodafone"},
	'721' => {:description=>"Mobile Vodafone"},
	'722' => {:description=>"Mobile Vodafone"},
	'723' => {:description=>"Mobile Vodafone"},
	'724' => {:description=>"Mobile Vodafone"},
	'725' => {:description=>"Mobile Vodafone"},
	'726' => {:description=>"Mobile Vodafone"},
	'727' => {:description=>"Mobile Vodafone"},
	'728' => {:description=>"Mobile Vodafone"},
	'729' => {:description=>"Mobile Vodafone"},
	'730' => {:description=>"Mobile Vodafone"},
	'731' => {:description=>"Mobile Vodafone"},
	'732' => {:description=>"Mobile Vodafone"},
	'733' => {:description=>"Mobile Vodafone"},
	'734' => {:description=>"Mobile Vodafone"},
	'735' => {:description=>"Mobile Vodafone"},
	'736' => {:description=>"Mobile Vodafone"},
	'737' => {:description=>"Mobile Vodafone"},
	'739' => {:description=>"Mobile Vodafone"},
	'740' => {:description=>"Mobile Orange"},
	'741' => {:description=>"Mobile Orange"},
	'742' => {:description=>"Mobile Orange"},
	'743' => {:description=>"Mobile Orange"},
	'744' => {:description=>"Mobile Orange"},
	'745' => {:description=>"Mobile Orange"},
	'746' => {:description=>"Mobile Orange"},
	'747' => {:description=>"Mobile Orange"},
	'748' => {:description=>"Mobile Orange"},
	'749' => {:description=>"Mobile Orange"},
	'750' => {:description=>"Mobile Orange"},
	'751' => {:description=>"Mobile Orange"},
	'752' => {:description=>"Mobile Orange"},
	'753' => {:description=>"Mobile Orange"},
	'754' => {:description=>"Mobile Orange"},
	'755' => {:description=>"Mobile Orange"},
	'756' => {:description=>"Mobile Orange"},
	'757' => {:description=>"Mobile Orange"},
	'758' => {:description=>"Mobile Orange"},
	'759' => {:description=>"Mobile Orange"},
	'760' => {:description=>"Mobile Cosmote"},
	'761' => {:description=>"Mobile Cosmote"},
	'762' => {:description=>"Mobile Cosmote"},
	'763' => {:description=>"Mobile Cosmote"},
	'764' => {:description=>"Mobile Cosmote"},
	'765' => {:description=>"Mobile Cosmote"},
	'766' => {:description=>"Mobile Cosmote"},
	'767' => {:description=>"Mobile Cosmote"},
	'768' => {:description=>"Mobile Cosmote"},
	'769' => {:description=>"Mobile Cosmote"},
	'770' => {:description=>"Mobile RCS & RDS"},
	'771' => {:description=>"Mobile RCS & RDS"},
	'772' => {:description=>"Mobile RCS & RDS"},
	'773' => {:description=>"Mobile RCS & RDS"},
	'780' => {:description=>"Mobile Telemobil"},
	'784' => {:description=>"Mobile Cosmote"},
	'785' => {:description=>"Mobile Cosmote"},
	'786' => {:description=>"Mobile Cosmote"},
	'788' => {:description=>"Mobile Telemobil"},
	'799' => {:description=>"Mobile Vodafone"}
}