# encoding: utf-8
# Romania uses different NDC for the former monopoly (Romtelecom) and other operators (OLO - Other line operators)
# Landline starting with 2 usually mean Romtelecom, starting with 3 means OLO. 

Romania = {
	:range => 1..3,
	:default => 3,
	'21' => {:description=>"București"},
	'31' => {:description=>"București"},
	'256' => {:description=>"Timișoara"},
	'356' => {:description=>"Timișoara"},
	'711' => {:description=>"Romtelecom VoIP"},
	'720' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'721' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'722' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'723' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'724' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'725' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'726' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'727' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'728' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'729' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'730' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'731' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'732' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'733' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'734' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'735' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'736' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'737' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'739' => {:description=>"Mobile Vodafone", :is_mobile=>true},
	'740' => {:description=>"Mobile Orange", :is_mobile=>true},
	'741' => {:description=>"Mobile Orange", :is_mobile=>true},
	'742' => {:description=>"Mobile Orange", :is_mobile=>true},
	'743' => {:description=>"Mobile Orange", :is_mobile=>true},
	'744' => {:description=>"Mobile Orange", :is_mobile=>true},
	'745' => {:description=>"Mobile Orange", :is_mobile=>true},
	'746' => {:description=>"Mobile Orange", :is_mobile=>true},
	'747' => {:description=>"Mobile Orange", :is_mobile=>true},
	'748' => {:description=>"Mobile Orange", :is_mobile=>true},
	'749' => {:description=>"Mobile Orange", :is_mobile=>true},
	'750' => {:description=>"Mobile Orange", :is_mobile=>true},
	'751' => {:description=>"Mobile Orange", :is_mobile=>true},
	'752' => {:description=>"Mobile Orange", :is_mobile=>true},
	'753' => {:description=>"Mobile Orange", :is_mobile=>true},
	'754' => {:description=>"Mobile Orange", :is_mobile=>true},
	'755' => {:description=>"Mobile Orange", :is_mobile=>true},
	'756' => {:description=>"Mobile Orange", :is_mobile=>true},
	'757' => {:description=>"Mobile Orange", :is_mobile=>true},
	'758' => {:description=>"Mobile Orange", :is_mobile=>true},
	'759' => {:description=>"Mobile Orange", :is_mobile=>true},
	'760' => {:description=>"Mobile Cosmote", :is_mobile=>true},
	'761' => {:description=>"Mobile Cosmote", :is_mobile=>true},
	'762' => {:description=>"Mobile Cosmote", :is_mobile=>true},
	'763' => {:description=>"Mobile Cosmote", :is_mobile=>true},
	'764' => {:description=>"Mobile Cosmote", :is_mobile=>true},
	'765' => {:description=>"Mobile Cosmote", :is_mobile=>true},
	'766' => {:description=>"Mobile Cosmote", :is_mobile=>true},
	'767' => {:description=>"Mobile Cosmote", :is_mobile=>true},
	'768' => {:description=>"Mobile Cosmote", :is_mobile=>true},
	'769' => {:description=>"Mobile Cosmote", :is_mobile=>true},
	'770' => {:description=>"Mobile RCS & RDS", :is_mobile=>true},
	'771' => {:description=>"Mobile RCS & RDS", :is_mobile=>true},
	'772' => {:description=>"Mobile RCS & RDS", :is_mobile=>true},
	'773' => {:description=>"Mobile RCS & RDS", :is_mobile=>true},
	'780' => {:description=>"Mobile Telemobil", :is_mobile=>true},
	'784' => {:description=>"Mobile Cosmote", :is_mobile=>true},
	'785' => {:description=>"Mobile Cosmote", :is_mobile=>true},
	'786' => {:description=>"Mobile Cosmote", :is_mobile=>true},
	'788' => {:description=>"Mobile Telemobil", :is_mobile=>true},
	'799' => {:description=>"Mobile Vodafone", :is_mobile=>true}
}